# Generated by Django 2.2.15 on 2021-08-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='added_field',
            field=models.TextField(blank=True, null=True, verbose_name='Добавленое поле'),
        ),
    ]
