# Generated by Django 2.2.15 on 2021-08-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210803_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='added_field',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
    ]
